mod gc;
mod infrastructure;
mod machine;
mod memory;
mod parser;
mod representation;

use crate::machine::basic_machine::BasicMachine;
use gc::garbage_collector::garbage_collector;
use infrastructure::{register, stack::Stack};
use memory::memory::Memory;
use representation::type_system::Object;

fn main() {
    let mut m = Memory::new(8);
    let car_0 = Object::Pair(1);
    let cdr_0 = Object::Pair(3);
    let car_1 = Object::Integer(1);
    let cdr_1 = Object::Pair(2);
    let car_2 = Object::Integer(2);
    let cdr_2 = Object::Nil;
    let car_3 = Object::Pair(4);
    let cdr_3 = Object::Nil;
    let car_4 = Object::Integer(3);
    let cdr_4 = Object::Pair(5);
    let car_5 = Object::Pair(6);
    let cdr_5 = Object::Nil;
    let car_6 = Object::Integer(4);
    let cdr_6 = Object::Pair(7);
    let car_7 = Object::Integer(5);
    let cdr_7 = Object::Nil;
    m.update("car", car_0, 0);
    m.update("cdr", cdr_0, 0);
    m.update("car", car_1, 1);
    m.update("cdr", cdr_1, 1);
    m.update("car", car_2, 2);
    m.update("cdr", cdr_2, 2);
    m.update("car", car_3, 3);
    m.update("cdr", cdr_3, 3);
    m.update("car", car_4, 4);
    m.update("cdr", cdr_4, 4);
    m.update("car", car_5, 5);
    m.update("cdr", cdr_5, 5);
    m.update("car", car_6, 6);
    m.update("cdr", cdr_6, 6);
    m.update("car", car_7, 7);
    m.update("cdr", cdr_7, 7);
    println!("{}", m);
    let mut machine = BasicMachine::new();
    machine.initilize_registers();
    let item = Object::Index(0);
    machine.set_register_contents("root", item);
    let reg = machine.get_register("root").unwrap();
    reg.print_list(&m);
}
